[tool.poetry]
name = "study-webserver"
version = "0.1.0"
description = ""
authors = ["Jihoon Lee <jihoon.lee@10bms.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
